name: Docker Image CI Test Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Replace tokens  
      uses: cschleiden/replace-tokens@v1.2
      with:          
        tokenPrefix:  '#{'         
        tokenSuffix:  '}#'          
        files:  '["**/*.Dockerfile"]' 
      env:
        BUILD_IMAGE: mcr.microsoft.com/dotnet/core/sdk:3.1
        BASE_IMAGE: mcr.microsoft.com/windows/nanoserver:1809      
    
    - uses: actions/checkout@v3  
    - name: Build the Docker CM image
      run: docker build . --file examples/helix-basic-aspnetcore/Dockerfile --tag my-image-name:$(date +%s)
